version: '3'
services:
  web:
    image: nginx
    volumes:
     - ./nginx/templates:/etc/nginx/templates
    ports:
     - "8080:80"
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
     - "3000:3000"
