spring:
  graphql:
    graphiql:
      enabled: true
      path: /graphiql
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:pokedex;MODE=MYSQL
    username: root
    password: password
  h2:
    console:
      enabled: true
logging:
  level:
    root: DEBUG